// packages
import {
  Dices,
  Wallet,
  CircleDollarSign,
  HandCoins,
  ChartNoAxesColumn,
  ReceiptText,
  Network,
  Star,
  Trophy
} from "lucide-react";

// types
import { RouteProps } from "@/types/routes-types";

// pages
import Home from "@/pages/Home";
// import Sessions from "@/STDBY/Sessions";
// import Campaigns from "@/STDBY/Campaigns";
// import CampaignDetails from '@/STDBY/CampaignDetails'

export const routes: RouteProps[] = [
  {
    name: "Sorteio Ao Vivo",
    path: "/home",
    group: "Jogos",
    icon: Dices,
    category: "page",
    component: Home,
    disabled: () => false,
    showOnHome: () => false,
    showOnSideDrawer: () => true,
    showOnTopbar: () => false,
  },
  {
    name: "Rodadas Especiais",
    path: "/rodadas-especiais",
    group: "Jogos",
    icon: Star,
    category: "page",
    component: Home,
    disabled: () => false,
    showOnHome: () => false,
    showOnSideDrawer: () => true,
    showOnTopbar: () => false,
  },
  {
    name: "Extrato",
    path: "/extrato",
    group: "Controle",
    icon: ReceiptText,
    description: ``,
    category: "page",
    component: Home,
    disabled: () => true,
    showOnHome: () => true,
    showOnSideDrawer: () => true,
    showOnTopbar: () => false,
  },
  {
    name: "Minhas Indicações",
    path: "/indicacoes",
    group: "Premiações",
    icon: Network,
    description: ``,
    category: "page",
    component: Home,
    disabled: () => true,
    showOnHome: () => true,
    showOnSideDrawer: () => true,
    showOnTopbar: () => false,
  },
  {
    name: "Minhas Cartelas",
    path: "/cartelas",
    group: "Premiações",
    icon: Trophy,
    description: ``,
    category: "page",
    component: Home,
    disabled: () => true,
    showOnHome: () => true,
    showOnSideDrawer: () => true,
    showOnTopbar: () => false,
  },
  {
    name: "Meus Ganhos",
    path: "/ganhos",
    group: "Histórico",
    icon: CircleDollarSign,
    description: ``,
    category: "page",
    component: Home,
    disabled: () => true,
    showOnHome: () => true,
    showOnSideDrawer: () => true,
    showOnTopbar: () => false,
  },
  {
    name: "Meus Depósitos",
    path: "/depositos",
    group: "Histórico",
    icon: HandCoins,
    description: ``,
    category: "page",
    component: Home,
    disabled: () => true,
    showOnHome: () => true,
    showOnSideDrawer: () => true,
    showOnTopbar: () => false,
  },
  {
    name: "Meus Jogos",
    path: "/jogos",
    group: "Histórico",
    icon: ChartNoAxesColumn,
    description: ``,
    category: "page",
    component: Home,
    disabled: () => true,
    showOnHome: () => true,
    showOnSideDrawer: () => true,
    showOnTopbar: () => false,
  },
  {
    name: "Depositar",
    path: "/depositar",
    icon: Wallet,
    category: "page",
    highlight: true,
    button: true,
    disabled: () => false,
    showOnHome: () => false,
    showOnSideDrawer: () => false,
    showOnTopbar: () => true,
  },
];
